version: '3'

services:
  db_mysql:
    # IOS m1칩 사용자는 아래 (platform: linux/x86_64) 주석을 풀고 실행해주세요 / 다른 분은 주석으로 해주시고 실행해주세요
    # platform: linux/x86_64
    build:
      context: ./db_mysql
      dockerfile: ./mysql.Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: BlackPizza
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_unicode_ci
    restart: always
  back:
    depends_on:
      - db_mysql
    build: ./back
    ports: 
      - "8000:5000"
    volumes:
      - ./back:/app
    environment:
      FLASK_ENV: development
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/src/app
    depends_on:
      - back